# Generated by Django 5.1.7 on 2025-05-23 02:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('address_street', models.CharField(max_length=150, verbose_name='Rua')),
                ('address_number', models.CharField(max_length=10, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, max_length=50, verbose_name='Complemento')),
                ('address_city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('address_state', models.CharField(max_length=50, verbose_name='Estado')),
                ('address_zipcode', models.CharField(max_length=20, verbose_name='CEP')),
                ('viewed', models.BooleanField(default=False)),
                ('visit_reason', models.CharField(choices=[('emergency', 'Emergência'), ('surgery', 'Cirurgia'), ('scheduled_exam', 'Exame Agendado'), ('consultation', 'Consulta'), ('other', 'Outro')], max_length=20, verbose_name='Motivo da visita')),
                ('arrival_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de chegada')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de atendimento')),
                ('last_visit', models.DateTimeField(blank=True, null=True, verbose_name='Data da última consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(blank=True, max_length=20, null=True)),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pep.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.CharField(choices=[('consulta', 'Consulta'), ('exame', 'Exame')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pep.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pep.patient')),
            ],
            options={
                'unique_together': {('professional', 'date', 'time')},
            },
        ),
    ]
